import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Sidebar from '@/components/Sidebar';
import Navbar from '@/components/Navbar';
import { ReduxProvider } from '@/redux/Provider';
import ToasterProvider from '@/components/ToasterProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <ReduxProvider>
          <ToasterProvider />

          <Sidebar />

          {/* Main content area with Navbar and page content */}
          <div className='ml-52'>
            <Navbar />
            <main className=''>{children}</main>
          </div>
        </ReduxProvider>

        {/* <main className='w-full'>{children}</main> */}
        {/* {children} */}
      </body>
    </html>
  );
}
